# Build base image
FROM python:3.11-slim AS base

# install poetry
RUN pip install poetry

# Set working directory
WORKDIR /app

# Copy only pyproject.toml and poetry.lock for poetry usage to leverage build caching
COPY pyproject.toml ./

# Install python dependencies
RUN poetry config virtualenvs.create false && \
    poetry install --no-dev --no-root

# Build the python app & the whole dependecies in middleware image
FROM base AS build

# Copy the whole app
COPY . .

# Build the app and extract the tar to /app
RUN poetry build && \
    tar xzf dist/*.tar.gz -C /app && \
    mv /app/*/app/* /app/

# Final image with only the app
FROM base AS final

COPY --from=build /app /app

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
