version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./pipeline_scripts:/var/jenkins_home/pipeline_scripts
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    command: bash -c "chown -R jenkins:jenkins /var/jenkins_home && /usr/local/bin/jenkins.sh"